# Generated by Django 5.2.1 on 2025-06-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Language code (e.g., 'en', 'ru', 'es')", max_length=10, unique=True)),
                ('name_english', models.CharField(help_text='Language name in English', max_length=100)),
                ('name_native', models.CharField(help_text='Language name in its native language', max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this language is enabled and available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name_english'],
            },
        ),
    ]
