# Generated by Django 5.2.2 on 2025-06-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name_english'], 'verbose_name': 'Language', 'verbose_name_plural': 'Языки для изучения'},
        ),
    ]
