# Generated by Django 5.2.2 on 2025-06-09 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_language',
            field=models.ForeignKey(blank=True, help_text='Currently active language for learning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='languages.language'),
        ),
        migrations.AddField(
            model_name='user',
            name='interface_language',
            field=models.ForeignKey(blank=True, help_text='Language for user interface', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interface_users', to='languages.language'),
        ),
        migrations.AddField(
            model_name='user',
            name='native_language',
            field=models.ForeignKey(blank=True, help_text="User's native language", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_users', to='languages.language'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify',
            field=models.BooleanField(default=True, help_text='Enable notifications'),
        ),
    ]
