# Generated by Django 5.2.2 on 2025-06-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_languageprogress'),
    ]

    operations = [
    ]
