# Generated by Django 5.2.2 on 2025-06-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_wordsprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailactivationtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Токен активации аккаунта', 'verbose_name_plural': 'Токены активации аккаунта'},
        ),
        migrations.AlterModelOptions(
            name='languageprogress',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Прогресс изучения языка', 'verbose_name_plural': 'Прогресс изучения языка'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='wordsprogress',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Прогресс изучения слов', 'verbose_name_plural': 'Прогресс изучения слов'},
        ),

    ]
