# Generated by Django 5.2.2 on 2025-06-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_emailactivationtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageprogress',
            name='learned_words_count',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of learned words (0.00 to 100.00)', max_digits=5),
        ),
    ]
