# Generated by Django 5.2.2 on 2025-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_languageprogress_learned_words_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languageprogress',
            old_name='learned_words_count',
            new_name='learned_words',
        ),
        migrations.RemoveField(
            model_name='languageprogress',
            name='learned_phrases_count',
        ),
        migrations.AddField(
            model_name='languageprogress',
            name='learned_phrases',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of learned phrases (0.00 to 100.00)', max_digits=5),
        ),
    ]
