# Generated by Django 5.2.2 on 2025-06-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageprogress',
            name='learned_phrases_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of learned phrases'),
        ),
        migrations.AddField(
            model_name='languageprogress',
            name='learned_words_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of learned words'),
        ),
    ]
