# Generated by Django 5.2.2 on 2025-06-14 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_options'),
        ('users', '0009_languageprogress_learned_phrases_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Full name of the user', max_length=150),
        ),
        migrations.AlterField(
            model_name='wordsprogress',
            name='target_language',
            field=models.ForeignKey(help_text='Язык, который изучается', on_delete=django.db.models.deletion.CASCADE, related_name='words_progress_target', to='languages.language'),
        ),
    ]
