# Generated by Django 5.2.2 on 2025-06-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_username_user_name_and_more'),
    ]

    operations = [
    ]
