# Generated by Django 5.2.2 on 2025-06-15 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_options'),
        ('users', '0013_quizprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizprogress',
            options={'ordering': ['-created_at'], 'verbose_name': 'Прогресс викторины', 'verbose_name_plural': 'Прогресс викторин'},
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='language',
            field=models.ForeignKey(help_text='Язык викторины', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_progress', to='languages.language'),
        ),
        migrations.AlterField(
            model_name='quizprogress',
            name='total_questions',
            field=models.PositiveIntegerField(help_text='Общее количество вопросов в викторине'),
        ),
    ]
