# Generated by Django 5.2.1 on 2025-06-09 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('parts_of_speech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Само слово', max_length=200)),
                ('transcription', models.CharField(blank=True, help_text='Транскрипция слова', max_length=300)),
                ('gender', models.CharField(blank=True, choices=[('masculine', 'Мужской'), ('feminine', 'Женский'), ('neuter', 'Средний'), ('common', 'Общий')], help_text='Род слова (необязательно)', max_length=20, null=True)),
                ('audio_url', models.URLField(blank=True, help_text='URL аудиофайла с произношением')),
                ('active', models.BooleanField(default=True, help_text='Активно ли слово')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(help_text='Язык слова', on_delete=django.db.models.deletion.CASCADE, related_name='words', to='languages.language')),
                ('part_of_speech', models.ForeignKey(help_text='Часть речи', on_delete=django.db.models.deletion.CASCADE, related_name='words', to='parts_of_speech.partofspeech')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='WordExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_text', models.TextField(help_text='Пример предложения с использованием слова')),
                ('translation', models.TextField(blank=True, help_text='Перевод примера')),
                ('audio_url', models.URLField(blank=True, help_text='URL аудиофайла с произношением примера')),
                ('active', models.BooleanField(default=True, help_text='Активен ли пример')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_language', models.ForeignKey(blank=True, help_text='Язык перевода примера', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_example_translations', to='languages.language')),
                ('word', models.ForeignKey(help_text='Слово, для которого приводится пример', on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='words.word')),
            ],
            options={
                'verbose_name': 'Пример использования слова',
                'verbose_name_plural': 'Примеры использования слов',
                'ordering': ['word', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=1.0, help_text='Уверенность в переводе (0.0 - 1.0)')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки о переводе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_word', models.ForeignKey(help_text='Исходное слово', on_delete=django.db.models.deletion.CASCADE, related_name='translations_as_source', to='words.word')),
                ('target_word', models.ForeignKey(help_text='Целевое слово (перевод)', on_delete=django.db.models.deletion.CASCADE, related_name='translations_as_target', to='words.word')),
            ],
            options={
                'verbose_name': 'Перевод слова',
                'verbose_name_plural': 'Переводы слов',
                'ordering': ['source_word__word', 'target_word__word'],
            },
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['word'], name='words_word_word_a2cf21_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['language'], name='words_word_languag_ce51b9_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['part_of_speech'], name='words_word_part_of_7c0332_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['active'], name='words_word_active_b5309b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('word', 'language')},
        ),
        migrations.AddIndex(
            model_name='wordexample',
            index=models.Index(fields=['word'], name='words_worde_word_id_72ab38_idx'),
        ),
        migrations.AddIndex(
            model_name='wordexample',
            index=models.Index(fields=['active'], name='words_worde_active_cb9d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='wordtranslation',
            index=models.Index(fields=['source_word'], name='words_wordt_source__acf613_idx'),
        ),
        migrations.AddIndex(
            model_name='wordtranslation',
            index=models.Index(fields=['target_word'], name='words_wordt_target__a5f002_idx'),
        ),
        migrations.AddIndex(
            model_name='wordtranslation',
            index=models.Index(fields=['confidence'], name='words_wordt_confide_a6866c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wordtranslation',
            unique_together={('source_word', 'target_word')},
        ),
    ]
