# Generated by Django 5.2.1 on 2025-06-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('parts_of_speech', '0001_initial'),
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Начинающий (A1-A2)'), ('elementary', 'Элементарный (A2-B1)'), ('intermediate', 'Средний (B1-B2)'), ('upper_intermediate', 'Выше среднего (B2-C1)'), ('advanced', 'Продвинутый (C1-C2)'), ('proficient', 'Профессиональный (C2+)')], default='beginner', help_text='Уровень сложности слова', max_length=30),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['difficulty_level'], name='words_word_difficu_11607f_idx'),
        ),
    ]
