# Generated by Django 5.2.1 on 2025-06-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', '(A1-A2)'), ('elementary', '(A2-B1)'), ('intermediate', '(B1-B2)'), ('upper_intermediate', '(B2-C1)'), ('advanced', '(C1-C2)'), ('proficient', '(C2+)')], default='beginner', help_text='Уровень сложности слова', max_length=30),
        ),
    ]
