# Generated by Django 5.2.2 on 2025-06-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_word_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'A1'), ('elementary', 'A2'), ('intermediate', 'B1'), ('upper_intermediate', 'B2'), ('advanced', 'C1'), ('proficient', 'C2')], default='beginner', help_text='Уровень сложности слова', max_length=30),
        ),
    ]
