# Generated by Django 5.2.2 on 2025-06-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_word_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio_url',
            field=models.CharField(blank=True, help_text='URL аудиофайла с произношением', max_length=255),
        ),
    ]
