# Generated by Django 5.2.1 on 2025-06-09 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Уникальный код части речи (например: 'noun', 'verb', 'adjective')", max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Описание части речи на английском языке')),
                ('enabled', models.BooleanField(default=True, help_text='Активна ли данная часть речи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Часть речи',
                'verbose_name_plural': 'Части речи',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PartOfSpeechTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название части речи на указанном языке', max_length=100)),
                ('abbreviation', models.CharField(blank=True, help_text="Сокращение части речи (например: 'сущ.', 'гл.', 'прил.')", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(help_text='Язык перевода', on_delete=django.db.models.deletion.CASCADE, related_name='part_of_speech_translations', to='languages.language')),
                ('part_of_speech', models.ForeignKey(help_text='Часть речи', on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='parts_of_speech.partofspeech')),
            ],
            options={
                'verbose_name': 'Перевод части речи',
                'verbose_name_plural': 'Переводы частей речи',
                'ordering': ['part_of_speech__code', 'language__code'],
                'unique_together': {('part_of_speech', 'language')},
            },
        ),
    ]
